# Setup containers for DataJoint elements environment ----------------------------------
# Basic usage:
#  > docker-compose --verbose up --detach
#  > docker-compose down
#  > docker-compose down --volumes
version: "2.4"
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: simple
    image: datajoint/mysql:5.7
    networks:
      djelem:
    platform: linux/amd64
    ports:
      - 6603:3306
    restart: always
    volumes:
      - sqldata:/var/lib/mysql

  conda:
    build:
      context: ../elements-image
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started # service_healthy
    environment:
      DJ_HOST: db
      DJ_PASS: simple
      DJ_USER: root
      GITHUB_USER: ${GITHUB_USER:-datajoint}
    init: true
    networks:
      djelem:
    ports:
      - 18888:8888
    volumes:
      - ./dev-container:/home/dj/datajoint-elements
      - vscode:/home/dj/.vscode-server/extensions
      - vscode-insiders:/home/dj/.vscode-server-insiders/extensions

networks:
  djelem:
    name: datajoint-elements-net-djelem

volumes:
  sqldata:
    name: datajoint-elements-vol-sqldata
  vscode:
    name: datajoint-elements-vol-vscode
  vscode-insiders:
    name: datajoint-elements-vol-vscode-insiders
