site_name: DataJoint Elements
dev_addr: '0.0.0.0:8000'
theme:
  name: cinder
  custom_dir: docs/themes/cinder-theme-ext
  disable_nav_previous_next: true
  disable_nav_search: false
  analytics:
    gtag: G-67GBDT81TP
nav:
  - index.md
  - publications.md
  - projects.md
  - 'Usage':
    - usage/design-principles.md
    - usage/adopt.md
    - Setup: usage/install.md
    - usage/glossary.md
  - 'Element Descriptions':
    - description/lab.md
    - description/animal.md
    - description/session.md
    - description/event.md
    - description/array_ephys.md
    - description/electrode_localization.md
    - description/calcium_imaging.md
    - description/miniscope.md
    - description/deeplabcut.md
    - description/visual_stimulus.md
    - description/facemap.md
  - 'Community':
    - community/contribute.md
    - community/nwb.md
    - community/support.md
  - 'Management and Policies':
    - management/plan.md
    - management/team.md
    - management/governance.md
    - management/selection.md
    - management/quality-assurance.md
    - management/outreach.md
    - management/licenses.md
markdown_extensions:
  - pymdownx.magiclink
  - mdx_truly_sane_lists
extra_css:
  - extra.css
plugins:
  - include-markdown
