site_name: DataJoint Elements
dev_addr: '0.0.0.0:8000'
theme:
  name: cinder
  custom_dir: themes/cinder-theme-ext
nav:
  - About: index.md
  - Setup: install.md
  - 'Management and Policies':
    - management/plan.md
    - management/team.md
    - management/governance.md
    - management/selection.md
    - management/quality-assurance.md
    - management/contribute.md
    - management/outreach.md
    - management/licenses.md
  - design-principles.md
  - adopt.md
  - support.md
  - glossary.md
markdown_extensions:
  - pymdownx.magiclink
  - mdx_truly_sane_lists
