name: Development
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v2
      - name: Compile docs static artifacts
        run: |
          docker-compose -f docker-compose-build.yaml up --exit-code-from app --build
      - name: Add docs static artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-static-datajoint-elements
          path: .mkdocs/site
          retention-days: 1
  publish-docs:
    if: github.event_name == 'push'
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch docs static artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-static-datajoint-elements
          path: .mkdocs/site
      - name: Commit documentation changes
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git \
              --branch gh-pages --single-branch gh-pages
          rm -R gh-pages/*
          cp -r .mkdocs/site/* gh-pages/
          touch gh-pages/.nojekyll
          echo "elements.datajoint.io" > gh-pages/CNAME
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --all
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{secrets.GITHUB_TOKEN}}
